name: final_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  just_audio: ^0.9.30
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  translator: ^0.1.7
  sqflite: ^2.2.0+3
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/read.png
    - assets/dictionary.png
    - assets/brain.png
    - assets/panda.png
    - assets/info.png
    - assets/translate.png

    - assets/data/kosa_kata.json
    - assets/data/category.json

    - assets/Suara/Angka/yay.mp3

    - assets/Suara/Umum/iya.mp3
    - assets/Suara/Umum/tidak.mp3
    - assets/Suara/Umum/maaf.mp3
    - assets/Suara/Umum/sama-sama.mp3
    - assets/Suara/Umum/terima-kasih.mp3

    - assets/Suara/Salam/namamu-siapa.mp3
    - assets/Suara/Salam/saya-baik-baik-saja.mp3
    - assets/Suara/Salam/senang-bertemu-denganmu.mp3
    - assets/Suara/Salam/senang-juga.mp3


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700